
[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"  # White background
secondaryBackgroundColor="#F0F2F6"  # Light grey secondary background
textColor="#31333F"  # Dark text color
font="sans serif"